#!/bin/bash

CONFIG_DIR="$HOME/.config/eww"
WIDGET_DIR="$CONFIG_DIR/windows"
OUTPUT_FILE="$CONFIG_DIR/eww.yuck"

OUTPUT_STYLE_FILE="$CONFIG_DIR/eww.scss"

# Header comment
echo ";; Auto-generated by gen.sh — don't edit manually!" > "$OUTPUT_FILE"
echo "// Auto-generated by gen.sh — don't edit manually!" > "$OUTPUT_STYLE_FILE"

# Include each .yuck file
for file in "$WIDGET_DIR"/*/index.yuck; do
    filename=$(basename $(dirname $file))
    echo "(include \"$WIDGET_DIR/$filename/index.yuck\")" >> "$OUTPUT_FILE"
    if [ -e "$WIDGET_DIR/$filename/style.scss" ]; then
        echo "@use \"$WIDGET_DIR/$filename/style.scss\" as *;" >> "$OUTPUT_STYLE_FILE"
    fi
done

