#!/bin/bash

CONFIG_DIR="$HOME/.config/eww"
WIDGET_DIR="$CONFIG_DIR/windows"
OUTPUT_FILE="$CONFIG_DIR/eww.yuck"

# Header comment
echo ";; Auto-generated by gen.sh — don't edit manually!" > "$OUTPUT_FILE"

# Include each .yuck file
for file in "$WIDGET_DIR"/*.yuck; do
    filename=$(basename "$file")
    if [[ "$filename" != "*.yuck" ]]; then
        echo "(include \"windows/$filename\")" >> "$OUTPUT_FILE"
    fi
done

