[mgr]
show_hidden = true
[opener]
edit = [{ run = "$EDITOR %s", block = true, desc = "Edit" }]
open = [{ run = "xdg-open %s1", desc = "Open", orphan = true }]
reveal = [{ run = "xdg-open %d1", desc = "Reveal", orphan = true }]
[open]
prepend_rules = [{ url = "*.m3u", use = ["play", "reveal", "edit"] }]
